### ISSUE TITLE
case definition too narrow

### ISSUE THREAD

**Issue by jboucsein** [EPIET/OutbreakInvestigation#2]
Case definition is messed-up: the initial setup is sensible, but in a later step everyone who has ANY missing data on cardinal symptoms is declared a non-case. This means that for example someone with 'vomiting' will be declared a non-case if info on 'bloody' is missing. I propose to declare only those as non-cases who participated in the meal and for which ALL info on cardinal symptoms is missing.

**Comment by AmyMikhail** [comment]
This has been resolved in the latest (2022) version.  

**Cases** are now defined as:

- Respondents who attended the meal
- developed ANY cardinal symptoms (at least one of diarrhoea, bloody or vomiting)
- had an onset date and time within 48 hours of the meal

**Non-cases** are now defined as:

- Respondents who attended the meal
- did not declare development of ANY cardinal symptoms on the survey (FALSE and/or NA for all three), OR
- did develop one or more symptoms of interest, but onset was outside of the 48 hour period of interest.

The only people that are excluded from analysis now are those that did not have the meal (*n* = 13).
